######################################################################
# Automatically generated by qmake (2.01a) ?? 6? 16 16:05:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWidget.h
SOURCES += main.cpp MainWidget.cpp
RESOURCES += resource.qrc
